// Generated by nitro
import type { Serialize, Simplify } from 'nitropack/types';
declare module 'nitropack/types' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T;
  interface InternalApi {
    '/__nuxt_error': {
      default: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../../../node_modules/.pnpm/nuxt@3.17.2_@parcel+watcher@2.5.1_@types+node@22.15.17_db0@0.3.2_eslint@9.26.0_jiti@2.4_5c0abc3862bdbd2a062081184b1842bb/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default
            >
          >
        >
      >;
    };
    '/__nuxt_island/**': {
      default: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../server/#internal/nuxt/island-renderer').default
            >
          >
        >
      >;
    };
  }
}
export {};
