packages:
  - packages/*
  - apps/*
  - docs

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@octokit/plugin-paginate-rest@>=1.0.0 <9.2.2': '>=9.2.2'
  '@octokit/request-error@>=1.0.0 <5.1.1': '>=5.1.1'
  '@octokit/request@>=1.0.0 <8.4.1': '>=8.4.1'
  devalue@<5.3.2: '>=5.3.2'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  node-forge@<1.3.2: '>=1.3.2'
  nuxt@>=3.6.0 <3.19.0: '>=3.19.0'
  playwright@<1.55.1: '>=1.55.1'
  storybook@>=9.0.0 <9.1.17: '>=9.1.17'
  tar@=7.5.1: '>=7.5.2'
  tmp@<=0.2.3: '>=0.2.4'
  valibot@>=0.31.0 <1.2.0: '>=1.2.0'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
  vite@>=7.1.0 <=7.1.4: '>=7.1.5'
