<script setup lang="ts">
  import { ref, computed } from 'vue';
  import { useData } from 'vitepress';
  import { gridExamples } from '../grid-examples';
  import { containerExamples } from '../container-examples';
  import { columnExamples } from '../column-examples';
  import { spacingExamples } from '../spacing-examples';
  import { zIndexExamples } from '../z-index-examples';
  import { textAlignExamples } from '../text-align-examples';
  import { widthExamples } from '../width-examples';
  import { borderExamples } from '../border-examples';
  import { aspectRatioExamples } from '../aspect-ratio-examples';
  import { transitionExamples } from '../transition-examples';
  import { shadowExamples } from '../shadow-examples';
  import { backgroundExamples } from '../background-examples';
  import { textColorExamples } from '../text-color-examples';
  import { typographyExamples } from '../typography-examples';
  import { sizingExamples } from '../sizing-examples';
  import { opacityExamples } from '../opacity-examples';
  import { interactivityExamples } from '../interactivity-examples';
  import { elementExamples } from '../element-examples';
  import { componentExamples } from '../component-examples';
  // @ts-ignore — virtual module generated by Vite plugin at build time
  import { highlightedExamples } from 'virtual:highlighted-examples';

  const allExamples: Record<string, string> = {
    ...gridExamples,
    ...containerExamples,
    ...columnExamples,
    ...spacingExamples,
    ...zIndexExamples,
    ...textAlignExamples,
    ...widthExamples,
    ...borderExamples,
    ...aspectRatioExamples,
    ...transitionExamples,
    ...shadowExamples,
    ...backgroundExamples,
    ...textColorExamples,
    ...typographyExamples,
    ...sizingExamples,
    ...opacityExamples,
    ...interactivityExamples,
    ...elementExamples,
    ...componentExamples,
  };

  const props = defineProps<{
    name?: string;
    code?: string;
    examples?: Record<string, string>;
  }>();

  const { isDark } = useData();

  const resolvedCode = computed(() => {
    if (props.code) return props.code;
    const source = props.examples ?? allExamples;
    if (props.name && props.name in source) return source[props.name];
    return '';
  });

  const highlightedHtml = computed(() => {
    if (props.name && props.name in highlightedExamples) {
      const entry = highlightedExamples[props.name];
      return isDark.value ? entry.dark : entry.light;
    }
    return '';
  });

  // Copy to clipboard
  const copied = ref(false);

  async function copyCode() {
    try {
      await navigator.clipboard.writeText(resolvedCode.value);
      copied.value = true;
      setTimeout(() => (copied.value = false), 2000);
    } catch {
      // Clipboard API unavailable
    }
  }

  const activeTab = ref<'code' | 'preview'>('preview');
</script>

<template>
  <div class="code-preview">
    <div class="code-preview__tabs">
      <button
        :class="['code-preview__tab', { active: activeTab === 'code' }]"
        @click="activeTab = 'code'"
      >
        Code
      </button>
      <button
        :class="['code-preview__tab', { active: activeTab === 'preview' }]"
        @click="activeTab = 'preview'"
      >
        Preview
      </button>
      <button
        v-if="activeTab === 'code'"
        class="code-preview__copy"
        @click="copyCode"
      >
        {{ copied ? 'Copied!' : 'Copy' }}
      </button>
    </div>

    <div v-show="activeTab === 'code'" class="code-preview__code">
      <div v-if="highlightedHtml" v-html="highlightedHtml" />
      <pre v-else><code>{{ resolvedCode }}</code></pre>
    </div>

    <div v-show="activeTab === 'preview'" class="code-preview__preview">
      <div v-html="resolvedCode" class="code-preview__result"></div>
    </div>
  </div>
</template>

<style scoped>
  .code-preview {
    margin: 1.25rem 0;
    border: 1px solid var(--vp-c-divider);
    border-radius: 8px;
    overflow: hidden;
  }

  .code-preview__tabs {
    display: flex;
    align-items: center;
    background: var(--vp-c-bg-soft);
    border-bottom: 1px solid var(--vp-c-divider);
  }

  .code-preview__tab {
    padding: 0.5rem 1rem;
    font-size: 0.875rem;
    background: none;
    border: none;
    color: var(--vp-c-text-2);
    cursor: pointer;
    border-bottom: 2px solid transparent;
  }

  .code-preview__tab:hover {
    color: var(--vp-c-text-1);
  }

  .code-preview__tab.active {
    color: var(--vp-c-brand-1);
    border-bottom-color: var(--vp-c-brand-1);
  }

  .code-preview__copy {
    margin-left: auto;
    margin-right: 0.5rem;
    padding: 0.25rem 0.75rem;
    font-size: 0.75rem;
    background: none;
    border: 1px solid var(--vp-c-divider);
    border-radius: 4px;
    color: var(--vp-c-text-2);
    cursor: pointer;
  }

  .code-preview__copy:hover {
    color: var(--vp-c-text-1);
    border-color: var(--vp-c-text-3);
  }

  .code-preview__code,
  .code-preview__preview {
    padding: 1rem;
    min-height: 80px;
  }

  .code-preview__code {
    background: var(--vp-code-block-bg);
    overflow-x: auto;
  }

  /* Fallback (plain text, used for inline code prop without pre-highlighting) */
  .code-preview__code pre {
    margin: 0;
    font-size: 0.8125rem;
    line-height: 1.5;
  }

  .code-preview__code code {
    font-family: var(--vp-font-family-mono);
    color: var(--vp-c-text-1);
  }

  /* Shiki output */
  .code-preview__code :deep(pre.shiki) {
    margin: 0;
    padding: 0;
    background: transparent !important;
    font-size: 0.8125rem;
    line-height: 1.5;
  }

  .code-preview__code :deep(pre.shiki code) {
    font-family: var(--vp-font-family-mono);
  }

  .code-preview__preview {
    background: var(--vp-c-bg-soft);
  }

  .code-preview__result {
    font-size: 0.875rem;
  }

  /* Generic: style children of any grid container in preview */
  .code-preview__result :deep([class*='grid']) > * {
    padding: 0.5rem 0.75rem;
    background: var(--vp-c-bg-soft);
    border: 1px dashed var(--vp-c-divider);
    border-radius: 4px;
  }

  /* Card children: slightly larger padding and radius */
  .code-preview__result :deep(.grid-cards) .card {
    padding: 0.75rem 1rem;
    border-radius: 6px;
  }

  /* Holy grail needs min-height to show the layout */
  .code-preview__result :deep(.grid-holy-grail) {
    min-height: 180px;
  }
</style>
