name: ✨ Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['enhancement', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving HäspenUI! Please fill out this template to help us understand your feature request.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please check the following before submitting this feature request
      options:
        - label: I have searched existing issues to make sure this feature hasn't been requested before
          required: true
        - label: I have read the [Contributing Guidelines](../CONTRIBUTING.md)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: I have also considered...

  - type: dropdown
    id: component-type
    attributes:
      label: Component Type
      description: What type of component or feature is this?
      options:
        - Atom (basic building block)
        - Molecule (simple group of atoms)
        - Organism (complex component)
        - Template (page layout)
        - Utility/Helper
        - Design Token
        - Composable/Hook
        - Tool/Build Process
        - Documentation
        - Other (specify below)

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature in your project
      placeholder: In my project, I would use this to...

  - type: textarea
    id: examples
    attributes:
      label: Examples/Mockups
      description: Provide examples, mockups, or references to similar implementations
      placeholder: Here are some examples or mockups...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete from your perspective?
      placeholder: |
        - [ ] Feature does X
        - [ ] Feature supports Y
        - [ ] Feature is accessible

  - type: checkboxes
    attributes:
      label: Would you like to work on this feature?
      description: Let us know if you're interested in contributing
      options:
        - label: I'd like to work on this feature myself
        - label: I can help with design/planning
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: Additional information...

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
